"""Add requester_vat_number and requester_country_code to Company

Revision ID: 691929cc5caa
Revises: 31dac865ce38
Create Date: 2025-09-25 18:06:01.013480

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '691929cc5caa'
down_revision = '31dac865ce38'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('companies', schema=None) as batch_op:
        batch_op.add_column(sa.Column('requester_vat_number', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('requester_country_code', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('companies', schema=None) as batch_op:
        batch_op.drop_column('requester_country_code')
        batch_op.drop_column('requester_vat_number')

    # ### end Alembic commands ###
